### ISSUE TITLE
Implement Email Notifications for Adding/Deleting Nodal Coordinators

### ISSUE THREAD

**Issue by mrudhvika940** [virtual-labs/app-outreach-tracker-web#10]
**Description**
Add a new feature to the Workshop Reporting Tool. When a Nodal Coordinator is added or deleted, an email notification should be sent to the Nodal Coordinator's email address.

**Requirements**
- Trigger email notification upon adding a new Nodal Coordinator.
- Trigger email notification upon deleting an existing Nodal Coordinator.
- Email should include relevant details:
- Ensure the email content is customizable via a template.
- Implement error handling for email delivery failures.
- Update documentation to reflect this new feature.

**Comment by 112Nisha** [comment]
The code for the website is now capable of sending mails when a user is added or removed by an admin
